# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: test_gRPC.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='test_gRPC.proto',
  package='test_gRPC',
  syntax='proto3',
  serialized_pb=_b('\n\x0ftest_gRPC.proto\x12\ttest_gRPC\"3\n\x14\x41n_exciting_response\x12\x1b\n\x13\x65xciting_response_1\x18\x01 \x01(\t\"G\n\x15\x41n_unexciting_request\x12\x16\n\x0erequest_name_1\x18\x01 \x01(\t\x12\x16\n\x0erequest_name_2\x18\x02 \x01(\t2^\n\ttest_gRPC\x12Q\n\nGetFeature\x12 .test_gRPC.An_unexciting_request\x1a\x1f.test_gRPC.An_exciting_response\"\x00\x62\x06proto3')
)




_AN_EXCITING_RESPONSE = _descriptor.Descriptor(
  name='An_exciting_response',
  full_name='test_gRPC.An_exciting_response',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='exciting_response_1', full_name='test_gRPC.An_exciting_response.exciting_response_1', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=30,
  serialized_end=81,
)


_AN_UNEXCITING_REQUEST = _descriptor.Descriptor(
  name='An_unexciting_request',
  full_name='test_gRPC.An_unexciting_request',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='request_name_1', full_name='test_gRPC.An_unexciting_request.request_name_1', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='request_name_2', full_name='test_gRPC.An_unexciting_request.request_name_2', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=83,
  serialized_end=154,
)

DESCRIPTOR.message_types_by_name['An_exciting_response'] = _AN_EXCITING_RESPONSE
DESCRIPTOR.message_types_by_name['An_unexciting_request'] = _AN_UNEXCITING_REQUEST
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

An_exciting_response = _reflection.GeneratedProtocolMessageType('An_exciting_response', (_message.Message,), dict(
  DESCRIPTOR = _AN_EXCITING_RESPONSE,
  __module__ = 'test_gRPC_pb2'
  # @@protoc_insertion_point(class_scope:test_gRPC.An_exciting_response)
  ))
_sym_db.RegisterMessage(An_exciting_response)

An_unexciting_request = _reflection.GeneratedProtocolMessageType('An_unexciting_request', (_message.Message,), dict(
  DESCRIPTOR = _AN_UNEXCITING_REQUEST,
  __module__ = 'test_gRPC_pb2'
  # @@protoc_insertion_point(class_scope:test_gRPC.An_unexciting_request)
  ))
_sym_db.RegisterMessage(An_unexciting_request)



_TEST_GRPC = _descriptor.ServiceDescriptor(
  name='test_gRPC',
  full_name='test_gRPC.test_gRPC',
  file=DESCRIPTOR,
  index=0,
  options=None,
  serialized_start=156,
  serialized_end=250,
  methods=[
  _descriptor.MethodDescriptor(
    name='GetFeature',
    full_name='test_gRPC.test_gRPC.GetFeature',
    index=0,
    containing_service=None,
    input_type=_AN_UNEXCITING_REQUEST,
    output_type=_AN_EXCITING_RESPONSE,
    options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_TEST_GRPC)

DESCRIPTOR.services_by_name['test_gRPC'] = _TEST_GRPC

# @@protoc_insertion_point(module_scope)
